import type { UploadResponse } from "./api";

/**
 * Render a processed graph as a single Markdown document with Obsidian-style
 * [[wikilinks]]. Each concept becomes a heading whose title matches its link
 * text, so the file reads as one note today and splits cleanly into a vault of
 * linked notes (one per concept) when dropped into Obsidian.
 */
export function graphToMarkdown(result: UploadResponse): string {
  const graph = result.graph;
  if (!graph || !graph.nodes.length) return "# Knowledge Map\n\n_No concepts._\n";

  const labelById = new Map<string, string>();
  for (const n of graph.nodes) labelById.set(n.data.id, n.data.label);

  // Group connections by concept id.
  const outgoing = new Map<string, string[]>();
  for (const e of graph.edges) {
    const srcLabel = labelById.get(e.data.source);
    const tgtLabel = labelById.get(e.data.target);
    if (!srcLabel || !tgtLabel) continue;
    const rel = e.data.relationship_type.replace(/_/g, " ");
    const why = e.data.reasoning ? ` — ${e.data.reasoning}` : "";

    push(outgoing, e.data.source, `${rel} [[${tgtLabel}]]${why}`);
    push(outgoing, e.data.target, `[[${srcLabel}]] ${rel} this${why}`);
  }

  const title = (result.filename || "Knowledge Map").replace(/\.pdf$/i, "");
  const summary = result.global_understanding?.document_summary?.trim();

  const lines: string[] = [];
  lines.push(`# ${title} — Knowledge Map`);
  lines.push("");
  lines.push(
    `> Generated by Knowledge Mapper · ${graph.nodes.length} concepts · ${graph.edges.length} connections`
  );
  lines.push("");
  if (summary) {
    lines.push(summary);
    lines.push("");
  }
  lines.push("---");
  lines.push("");

  // Concepts, most important first.
  const nodes = [...graph.nodes].sort((a, b) => b.data.importance - a.data.importance);
  for (const n of nodes) {
    const d = n.data;
    lines.push(`## ${d.label}`);
    const meta = [
      `**Type:** ${d.concept_type}`,
      `**Role:** ${d.educational_role}`,
      d.domain ? `**Domain:** ${d.domain}` : null,
      `**Importance:** ${Math.round(d.importance * 100)}%`,
      d.is_hub ? `**Hub**` : null,
    ].filter(Boolean);
    lines.push(meta.join(" · "));
    lines.push("");
    if (d.summary) {
      lines.push(d.summary);
      lines.push("");
    }
    const conns = outgoing.get(d.id);
    if (conns && conns.length) {
      lines.push("**Connections:**");
      for (const c of conns) lines.push(`- ${c}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function push(map: Map<string, string[]>, key: string, value: string) {
  const arr = map.get(key);
  if (arr) arr.push(value);
  else map.set(key, [value]);
}

/** Trigger a client-side download of text as a file. */
export function downloadText(filename: string, text: string, mime = "text/markdown") {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
